name: test-tutorials-python

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  test_tutorials:
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']

    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute python workflows from bash script
        env: 
          HOPSWORKS_API_KEY: ${{ secrets["HOPSWORKS_API_KEY_" + matrix.python-version.replace(".", "")] }}
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: ./scripts/test-notebooks.sh